class Color(DefaultColor):
    DATETIME_FG = 238
    DATETIME_BG = 67

    USERNAME_FG = 246
    USERNAME_BG = 236
    USERNAME_ROOT_BG = 1

    HOSTNAME_FG = 248
    HOSTNAME_BG = 238

    HOME_SPECIAL_DISPLAY = True
    HOME_FG = 250
    HOME_BG = 240
    PATH_FG = 252
    PATH_BG = 242
    SEPARATOR_FG = 246
    CWD_FG = 15

    READONLY_FG = 15
    READONLY_BG = 1

    REPO_CLEAN_FG = 0  # black
    REPO_CLEAN_BG = 2  # green
    REPO_DIRTY_FG = 15 # white
    REPO_DIRTY_BG = 1  # red

    JOBS_FG = 14
    JOBS_BG = 8

    CMD_PASSED_FG = 15
    CMD_PASSED_BG = 244
    CMD_PASSED_BG2 = 239
    CMD_FAILED_FG = 0
    CMD_FAILED_BG = 217
    CMD_FAILED_BG2 = 210

    SVN_CHANGES_FG = REPO_DIRTY_FG
    SVN_CHANGES_BG = REPO_DIRTY_BG

    VIRTUAL_ENV_FG = 0
    VIRTUAL_ENV_BG = 2

    FANCY_NEWLINE_FG = 246
    FANCY_NEWLINE_BG = 236
    # FANCY_NEWLINE_TAIL_FG = 236
    # FANCY_NEWLINE_TAIL_FG_OVER_RESET = 242
